name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Her gece yarısı çalışır
  workflow_dispatch:      # Manuel tetikleme için

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3  # ❗️v3 olduğunu unutma!
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
