name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Her gece yarısı çalışır
  workflow_dispatch:      # Manuel olarak başlatmak için

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
